### PR TITLE
Update to latest embassy-net

### PR DESCRIPTION
**Pull request by Gerharddc**
This patch updates picoserve and it's embassy examples to be compatible with the latest embassy-net interface. Since the embassy packages on crates.io are now very outdated, it was unfortunately necessary to use the github packages instead.

_Just for some added context:_ currently there are too many issues with the outdated version of embassy-stm32 on crates.io for it to be useful in my case. I thus had to resort to using the latest version from github which has now introduced breaking changes in embassy-net that require updates to picoserve.

### CODE REVIEW

**Comment by Gerharddc** [comment]
Oops, just noticed https://github.com/sammhicks/picoserve/pull/52 also tries to address this issue :) Seems it takes a different approach though which tries to still maintain compatibility with the old embassy interface by adding a feature

**Comment by kaspar030** [comment]
I just checked how similar our PR's should now look and realized that this PR has many more fixes (it also updates the examples...)

**Comment by Gerharddc** [comment]
@sammhicks any suggestions on how best to approach this?

**Comment by sammhicks** [comment]
Given how the API change is now released, my plan is to update the `picoserve` dependency on `embassy-net` to 0.5 after commiting the code changes suggested in https://github.com/sammhicks/picoserve/issues/57.

**Comment by sammhicks** [comment]
Resolved by 00266199e6db138fe61e64034671458ab2f4135d.

`picoserve` 0.13 uses `embassy-net` 0.5

**Pull request closed without merging**
